"""Markdown report export service."""

from backend.models.report import InnovationReport


def generate_markdown(report: InnovationReport) -> str:
    """Render a complete downloadable Markdown innovation brief."""
    lines = [
        f"# {report.title}",
        "",
        f"**Report ID:** {report.report_id}  ",
        f"**Generated:** {report.created_at}  ",
        f"**Dataset:** {report.dataset_version}",
        "",
        "## Executive Summary",
        "",
        report.summary,
        "",
        "## Problem Context",
        "",
        f"- **Sector:** {report.problem.sector}",
        f"- **Location:** {report.problem.location or 'Not specified'}",
        f"- **Budget:** {report.problem.budget}",
        f"- **Timeframe:** {report.problem.timeframe}",
        f"- **Problem:** {report.problem.text}",
        "",
        "## AI Analysis",
        "",
        f"- Readiness score: {report.analysis.readiness_score}/100",
        f"- Urgency score: {report.analysis.urgency_score}/100",
        f"- Keywords: {', '.join(report.analysis.keywords)}",
        "",
        "## Recommendations",
        "",
    ]
    for index, item in enumerate(report.recommendations, 1):
        lines.extend(
            [
                f"### {index}. {item.title}",
                "",
                item.rationale,
                "",
                f"- Impact score: {item.impact_score}/100",
                f"- Innovation score: {item.innovation_score}/100",
                f"- Confidence: {item.confidence:.0%}",
                f"- Estimated cost: {item.estimated_cost}",
                f"- Timeframe: {item.timeframe}",
                "",
                "**Action steps**",
                *[f"- {step}" for step in item.action_steps],
                "",
            ]
        )
    lines.extend(["## Policy Recommendations", ""])
    lines.extend(f"- {policy}" for policy in report.policy_recommendations)
    lines.extend(["", "## Evidence Register", ""])
    for evidence_item in report.evidence:
        lines.append(
            f"- **{evidence_item.title}** ({evidence_item.category}, {evidence_item.relevance:.0%} match): "
            f"{evidence_item.summary} Source: {evidence_item.source}"
        )
    lines.extend(
        [
            "",
            "---",
            "Generated by GovInnovate AI using local mock AI reasoning. "
            "Validate recommendations with relevant officials and communities before implementation.",
        ]
    )
    return "\n".join(lines)
