[git-cliff]
repository = "."
tag = "v*"
sort = "group"
sections = [
  {type = "feat", section = "Features"},
  {type = "fix", section = "Bug Fixes"},
  {type = "perf", section = "Performance Improvements"},
  {type = "docs", section = "Documentation"},
  {type = "style", section = "Style"},
  {type = "refactor", section = "Refactorings"},
  {type = "test", section = "Tests"},
  {type = "chore", section = "Chores"},
]
